# Kickr configuration file (https://github.com/kickr-dev/kickr)
# yaml-language-server: $schema=https://raw.githubusercontent.com/kickr-dev/kickr/beta/.schemas/kickr.v1.schema.json
version: 1
ci:
  provider: gitlab
  options:
    - kickr
  release: {}
exclude:
  - makefile
license: mit
maintainers:
  - name: u.kilianpaquier
platform: gitlab
